name: Windows RDP via Bore

on: [push]

jobs:
  rdp-setup:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP and Disable NLA
        run: |
          # تفعيل بروتوكول سطح المكتب البعيد
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          
          # إيقاف ميزة NLA التي تسبب فصل الاتصال عن ترمكس
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0
          
          # فتح جدار الحماية
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          New-NetFirewallRule -DisplayName "Allow RDP via Bore" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 3389

      - name: Create Admin User
        run: |
          net user kamel007 Kamel@123 /add
          net localgroup administrators kamel007 /add
          # إجبار الويندوز على جعل كلمة المرور دائمة ولا تنتهي
          Set-LocalUser -Name "kamel007" -PasswordNeverExpires $true

      - name: Download and Extract Bore
        run: |
          Invoke-WebRequest "https://github.com/ekzhang/bore/releases/download/v0.5.1/bore-v0.5.1-x86_64-pc-windows-msvc.zip" -OutFile bore.zip
          Expand-Archive bore.zip -DestinationPath .
          Remove-Item bore.zip

      - name: Start Bore Tunnel
        run: |
          Write-Output "===================================================="
          Write-Output "انتظر ثوانٍ ليتغير رقم المنفذ (Port) أدناه واستخدمه فوراً"
          Write-Output "Username: sifom4"
          Write-Output "Password: sifodz02"
          Write-Output "===================================================="
          
          .\bore.exe local 3389 --to bore.pub
